# -*- coding: utf-8 -*-
"""Text generation with Markov chains.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EY1-chIx4UZQyLvbHaAnYMK17wO7Vlgf
"""

import random
import re
from collections import defaultdict, Counter
from google.colab import files
import zipfile

uploaded = files.upload()

filename = list(uploaded.keys())[0]

# Unzip the uploaded file
with zipfile.ZipFile(filename, 'r') as zip_ref:
    # Assuming there's only one text file or a known name
    # I'll extract 'beautiful_stories_from_shakespeare_by_nesbit.txt' based on previous context
    text_file_name = 'beautiful_stories_from_shakespeare_by_nesbit.txt'
    zip_ref.extract(text_file_name)

# Now open and read the extracted text file
with open(text_file_name, "r", encoding="utf-8") as file:
    text = file.read()

print("Dataset Loaded Successfully!")
print("\nFirst 500 Characters:\n")
print(text[:500])

def preprocess(text):

    text = text.lower()

    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)

    words = text.split()

    return words

words = preprocess(text)

print("Total Words:", len(words))
print(words[:30])

def build_markov_chain(words, order=2):

    chain = defaultdict(list)

    for i in range(len(words)-order):

        key = tuple(words[i:i+order])

        next_word = words[i+order]

        chain[key].append(next_word)

    return chain

markov_chain = build_markov_chain(words)

print("States:", len(markov_chain))

count = 0

for key,value in markov_chain.items():

    print(key,"->",value[:5])

    count +=1

    if count==10:
        break

def generate_text(chain,length=50):

    current_state = random.choice(list(chain.keys()))

    generated = list(current_state)

    for i in range(length):

        current_key = tuple(generated[-2:])

        if current_key not in chain:
            break

        next_word = random.choice(chain[current_key])

        generated.append(next_word)

    return " ".join(generated)

paragraph = generate_text(markov_chain,100)

print(paragraph)

for i in range(5):

    print("="*80)

    print("Generated Text",i+1)

    print()

    print(generate_text(markov_chain,60))

    print()

generated_text = generate_text(markov_chain,200)

with open("generated_text.txt","w") as file:

    file.write(generated_text)

print("Generated text saved.")

files.download("generated_text.txt")

length = int(input("Enter number of words to generate: "))

print()

print(generate_text(markov_chain,length))

frequency = Counter(words)

print("Top 20 Frequent Words:\n")

for word,count in frequency.most_common(20):

    print(word,"->",count)

print("Total Words :",len(words))

print("Unique Words :",len(set(words)))

print("Vocabulary Size :",len(frequency))

print("Total States :",len(markov_chain))

while True:

    choice = input("Generate Text? (yes/no): ")

    if choice.lower()=="yes":

        print()

        print(generate_text(markov_chain,80))

        print()

    else:

        print("Program Ended.")

        break